
  /* THIS FILE IS AUTOGENERATED */
  export const config = {
  "leaves": [
    {
      "id": "653f3bd2-5735-4b18-bdb3-889ad93a9dd8",
      "leaves": [
        {
          "id": "1b76a319-56cc-456e-b039-8f2de493e20a",
          "leaves": [
            {
              "id": "cde6084f-edb3-494d-ae83-58c3d99f3c1a",
              "name": "ergerg",
              "href": "/foundation/animation-basics/wwgre"
            },
            {
              "id": "0bbd940c-f20e-4a44-b365-e8b84aa3ea5a",
              "name": "@keyframes",
              "href": "/foundation/animation-basics/nailing-keyframes"
            }
          ],
          "name": "Animation Basics"
        },
        {
          "id": "2306bb9d-bc87-4f65-bde2-63e214b07d2d",
          "leaves": [
            {
              "id": "5b3665ab-1e27-4317-9f2e-15f546e7ad4c",
              "name": "ergerg",
              "href": "/foundation/creek/ergerg"
            }
          ],
          "name": "Creek"
        }
      ],
      "name": "Foundation"
    },
    {
      "id": "fddbc469-8e0b-46f5-9fa1-7abb12c87a0b",
      "name": "Getting Started",
      "href": "/getting-started",
      "top": 0
    },
    {
      "id": "5a1cdb8e-c5d4-4012-a6d8-46743c9bd462",
      "leaves": [
        {
          "id": "8fb335cd-0ed4-4423-bd11-5c74aca85f05",
          "leaves": [
            {
              "id": "7a452e2e-d745-457f-b60e-1afafa4f93b0",
              "name": "Tether Elements",
              "href": "/horizon/anchor-positioning/tether-with-anchor-positioning"
            }
          ],
          "name": "Anchor Positioning"
        }
      ],
      "name": "Horizon"
    },
    {
      "id": "a85c3d48-6417-4390-96ed-82fa895eb8ea",
      "leaves": [
        {
          "id": "ee99376c-0953-4f70-95be-42f664a2e21f",
          "leaves": [
            {
              "id": "9c0923d1-1bee-4bd7-98f5-4660b6ad7aad",
              "name": "First Keyframe",
              "href": "/studio/css-animation/understanding-keyframes"
            },
            {
              "id": "0e71c8c5-e7cf-4371-9773-307e8150235c",
              "name": "WAAPI Intro",
              "href": "/studio/css-animation/intro-to-waapi"
            }
          ],
          "name": "Css Animation"
        }
      ],
      "name": "Studio"
    },
    {
      "name": "Newsletter",
      "href": "https://craftofui.substack.com/subscribe",
      "topLevel": 2,
      "id": "18a273b7-6242-4a34-8487-43f3a754d706"
    }
  ],
  "name": "The Craft of UI",
  "id": "5cfc808f-ce2a-4f35-9fb5-51e4f7cfc521"
};
